INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI000', 'Personal Notes', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI101', 'Introduction to Computer Science', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI102', 'Living With Technology', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI111', 'Programming and Algorithms I', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI144', 'Introduction to UNIX/Linux', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI211', 'Programming and Algorithms II', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI221', 'Assembly Language Programming', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI301', 'Computer’s Impact on Society', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI311', 'Algorithms and Data Structures', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI313', 'Mind in the Machine - Honors', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI315', 'Programming Languages', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI317', 'Linear Programming Applications', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI320', 'Computer Architecture', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI340', 'Operating Systems', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI344', 'Shell Programming', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI346', 'Introduction to Computer Networks and Network Management', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI351', 'Numerical Methods Programming', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI380', 'Machines, Brains, and Minds', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI381', 'Language, Intelligence, and Computation', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI389', 'Industry Internship', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI400', 'Computer Science Activity', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI430', 'Software Engineering 1', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI431', 'Software Engineering 2', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI444', 'Fundamental UNIX System Administration', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI465', 'Web Programming Fundamentals', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI490', 'Directed Programming Experience', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI498', 'Topics in Computer Science', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI499', 'Honors Research Project/Thesis', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI511', 'Object-Oriented Programming', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI515', 'Compiler Design', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI533', 'Object-Oriented Analysis & Design', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI540', 'Systems Programming', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI546', 'Advanced Network Management', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI547', 'Advanced Computer Networks', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI550', 'Theory of Computing', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI566', 'Computer Graphics Programming', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI567', 'Graphical User Interfaces', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI568', 'Digital Image Processing', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI569', 'Advanced Computer Graphics', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI580', 'Artificial Intelligence', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI583', 'Expert Systems and Applications', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI585', 'Robotics and Machine Intelligence', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI598', 'Advanced Topics in Computer Science', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI611', 'Distributed Computing', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI619', 'Topics in Programming Language Theory', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI620', 'Computer Architecture', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI629', 'Topics in Computer Architecture', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI630', 'Software Engineering - Grad', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI639', 'Topics in Software Engineering - Grad', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI640', 'Operating Systems - Grad', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI649', 'Topics in Networking', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI650', 'Design and Analysis of Algorithms', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI659', 'Topics in Computer Theory', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI669', 'Topics in Computer Graphics', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI679', 'Topics in Database Systems', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI682', 'Topics in Artificial Intelligence', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI693', 'Research Methods in Computer Science', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI697', 'Independent Study', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI698', 'Seminar in Advanced Topics', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI699', 'Master’s Project', '0', 'adben');
INSERT INTO `getNote`.`class` (`course_id`, `course_name`, `blocked`, `instructor`) VALUES ('CSCI700', 'Master’s Thesis', '0', 'adben');
